Green dot missions
rubyforgood/pet-rescue pull request #184
Opened 2023-09-21 18:50 UTC by jadekstewart3

### Describe your change in plain English.
Commented out all failing integration tests to achieve the green dot mission. Found no failing model tests (YAY). There are some failing controller tests that I would love to pair on with someone :)

### Link to the issue
#180

2023-09-21 19:24 UTC, edwinthinks requested changes

2023-09-21 19:24 UTC, edwinthinks commented on test/controllers/checklist_template_items_controller_test.rb
> +    # assert_response :success
Could you use use the `skip` method here so we can see which ones we skipped in the minitest output? Otherwise I think it can get buried :P

2023-09-21 23:01 UTC, kasugaijin commented
LGTM!

2023-09-22 11:24 UTC, edwinthinks approved these changes
[![https://lgtm.us](https://media.giphy.com/media/xT0BKvIDgNYugS3m3C/giphy.gif)](https://lgtm.us)

2023-09-22 11:44 UTC, edwinthinks commented
@kasugaijin @jadekstewart3 hey there! I noticed a few changes that needed to be made when I updated this with the main branch. Once it goes green, its going into main!

Thanks @jadekstewart3 for taking the charge towards this.

2023-09-22 11:45 UTC, merged