Add licence file
rubyforgood/pet-rescue pull request #23
Opened 2023-07-27 13:43 UTC by thezeeshann

### Add a license file.

issue fixed #18

2023-07-27 21:09 UTC, nsiwnf approved these changes
lgtm!

2023-07-27 22:45 UTC, nsiwnf commented on LICENCE
> +Copyright (c) [year] [fullname]
2023 Ruby for Good

2023-07-27 22:45 UTC, nsiwnf requested changes
fill in placeholders

2023-07-28 00:31 UTC, edwinthinks approved these changes

2023-07-28 00:31 UTC, merged