362 pet tasks validations
rubyforgood/pet-rescue pull request #364
Opened 2023-12-08 20:01 UTC by jmilljr24

# 🔗 Issue

Resolves #362 
# ✍️ Description

Add migrations for null constraint for name in tasks. In task model add validation to name and description.

Adds tests for model validations.

# 📷 Screenshots/Demos

2023-12-08 20:14 UTC, jmilljr24 commented
The validations work as expected but I think a separate issue should be added for the front end modal to either prevent the user from clicking submit without the required information or have some sort of redirect. Right now if you hit submit, nothing is added to the db but there is a "content missing" in place of the model if you try to add a task after attempting to submit one without name/description.

I believe it's something to do with turbo-stream but I'm not sure exactly how to handle that. I'm sure there is something simple to prevent the form from being submitted. 

[https://jam.dev/c/4c29e57b-dd57-47c3-aa38-21d963d03c88](url)

2023-12-09 12:19 UTC, edwinthinks commented
@jmilljr24 yep that sounds like a good time to update the code so we are catching the invalid saving and respond back with the turbo frame saying there is an issue in the form. Would you like do it in the PR or merge this one and then do it in a seperate?

2023-12-09 12:20 UTC, edwinthinks requested changes

2023-12-09 12:20 UTC, edwinthinks commented on test/models/task_test.rb
> +  end
You can use https://github.com/thoughtbot/shoulda-matchers which makes this a bit faster  and less having to write our own tests.

2023-12-09 12:59 UTC, jmilljr24 commented
> @jmilljr24 yep that sounds like a good time to update the code so we are catching the invalid saving and respond back with the turbo frame saying there is an issue in the form. Would you like do it in the PR or merge this one and then do it in a seperate?

I'd prefer to merge this and have it be opened as a separate issue. Maybe someone else can take a stab at that. I might be able to cobble something together eventually but it might be a while.

2023-12-15 15:55 UTC, Ptrboro requested changes
I think we can simplify these migrations, we only need something like this:
```
class AddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
  def change
    change_column_null :tasks, :name, false
  end
end
```

Did you run into any issues and that's why you added check constraints?

2023-12-15 16:34 UTC, jmilljr24 commented
> I think we can simplify these migrations, we only need something like this:
> 
> ```
> class AddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
>   def change
>     change_column_null :tasks, :name, false
>   end
> end
> ```
> 
> Did you run into any issues and that's why you added check constraints?

Yes, I started with just the change_column_null. I don't remember the exact verbiage but basically I got an error saying not to do do that because if you make a change or rollback it will cause issues. There error output gave the suggestion I used. I also researched it and the check constraints prevent there from being any issues in the future.

2023-12-15 16:40 UTC, jmilljr24 commented
=====
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

=== Dangerous operation detected #strong_migrations ===

Setting NOT NULL on an existing column blocks reads and writes while every row is checked.
Instead, add a check constraint and validate it in a separate migration.

class AddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
  def change
    add_check_constraint :tasks, "name IS NOT NULL", name: "tasks_name_null", validate: false
  end
end

class ValidateAddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
  def up
    validate_check_constraint :tasks, name: "tasks_name_null"
    change_column_null :tasks, :name, false
    remove_check_constraint :tasks, name: "tasks_name_null"
  end

  def down
    add_check_constraint :tasks, "name IS NOT NULL", name: "tasks_name_null", validate: false
    change_column_null :tasks, :name, true
  end
end

2023-12-15 19:56 UTC, Ptrboro commented
@jmilljr24 I see, this is caused by the [strong_migrations](https://github.com/ankane/strong_migrations) gem. It makes sure we don't create any migrations that could be unsafe in a production environment. But as we don't have a production yet we don't need to worry about this.

To skip the error you have to wrap your code in `safety_assured` block like so:

```
class AddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
  def change
    safety_assured do
      change_column_null :tasks, :name, false
    end
  end
end
```

Btw @edwinthinks @kasugaijin what do you think about disabling this gem until we have production env? It doesn't give us any value now and just slows things down.

2023-12-15 20:59 UTC, kasugaijin commented
> @jmilljr24 I see, this is caused by the [strong_migrations](https://github.com/ankane/strong_migrations) gem. It makes sure we don't create any migrations that could be unsafe in a production environment. But as we don't have a production yet we don't need to worry about this.
> 
> To skip the error you have to wrap your code in `safety_assured` block like so:
> 
> ```
> class AddNotNullToNameInTasks < ActiveRecord::Migration[7.0]
>   def change
>     safety_assured do
>       change_column_null :tasks, :name, false
>     end
>   end
> end
> ```
> 
> Btw @edwinthinks @kasugaijin what do you think about disabling this gem until we have production env? It doesn't give us any value now and just slows things down.

100% I don't think it helps at all right now. Only hinders.

2023-12-16 14:22 UTC, Ptrboro approved these changes
LGTM! 👏

2023-12-19 22:50 UTC, edwinthinks approved these changes

2023-12-19 22:50 UTC, merged