Alexanderc360/issue747
rubyforgood/pet-rescue pull request #797
Opened 2024-06-01 21:27 UTC by alexanderc360

# 🔗 Issue
https://github.com/rubyforgood/pet-rescue/issues/747

# ✍️ Description
Added filters for pet age and breed

# 📷 Screenshots/Demos
![image](https://github.com/rubyforgood/pet-rescue/assets/33144250/45bc2bcc-a06b-420d-885b-4aad73354b3e)
![image](https://github.com/rubyforgood/pet-rescue/assets/33144250/8184bb05-0931-4452-ac94-631dee821f06)

2024-06-04 21:11 UTC, mononoken commented
@all-contributors

please add @alexanderc360 for code

2024-06-04 22:29 UTC, mononoken requested changes
I have two small comments to address before merging. Otherwise, this is excellent! I appreciate the hard work on this one. Getting this done without any prior experience with Ruby is impressive! You had to onboard to a new lang, framework, and multiple gems all at once. Thank you, @alexanderc360 !

2024-06-04 22:29 UTC, mononoken commented on app/views/organizations/adoptable_pets/index.html.erb
> +              </div>
We can remove this filter option. All the pets on this page should be unadopted as we don't want to show publicly the info of pets that are adopted.

2024-06-04 22:29 UTC, mononoken commented on app/views/organizations/adoptable_pets/index.html.erb
> +          <div class='d-flex justify-content-center align-items-center flex-wrap mb-3'>
Lets add a few bootstrap classes here to make the filter div look more in line with the screenshot in the issue:
```html
          <div class='d-flex justify-content-center align-items-center flex-wrap mb-3 p-4 rounded-5 bg-white'>
```

2024-06-04 22:29 UTC, mononoken commented on app/controllers/organizations/adoptable_pets_controller.rb
> +      items: 9
Good thinking using 9 instead of 10 for better visual.

2024-06-04 22:29 UTC, mononoken commented on app/controllers/organizations/adoptable_pets_controller.rb
> +    end
nice

2024-06-13 04:44 UTC, sevilla commented
@alexanderc360 I have some time and I am happy to assist with the code review comments from @mononoken if you want me to.

2024-06-13 15:17 UTC, alexanderc360 commented
@sevilla I appreciate the offer, however it's actually on my list of things to do this weekend. Thanks!

2024-06-19 00:13 UTC, kasugaijin commented
@alexanderc360 FYI some tests failed :)

2024-06-20 03:30 UTC, alexanderc360 commented
@mononoken I made the changes you requested. Sorry for closing the ticket earlier, that was a mistake.

2024-06-25 05:25 UTC, mononoken approved these changes
Thanks for picking up the comments!

2024-06-25 05:42 UTC, merged